services:
  database:
    container_name: ${MYSQL_DATABASE}
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/html/api/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  vue:
    build:
      dockerfile: ./docker/vue/Dockerfile
      context: .
    volumes:
    - ./client:/var/www/html/client/
    ports:
      - "5173:5173"
    command: "npm run dev"
